steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '-t'
      - 'gcr.io/$PROJECT_ID/universal-bridge'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/universal-bridge'
