/**
 * POST /api/process — Main processing route
 *
 * Accepts text, voice transcripts, or base64-encoded images and returns
 * a structured action plan generated by Google Gemini AI.
 *
 * Security layers applied in order:
 *   1. Firebase ID token verification (verifyFirebaseToken middleware)
 *   2. Per-user rate limiting (20 req/min via express-rate-limit)
 *   3. Input validation (content or imageData must be present)
 *
 * All successful requests are logged to Cloud Firestore for audit and
 * analytics purposes (non-blocking — failures are warned but not fatal).
 */
import { Router } from 'express';
import { rateLimit } from 'express-rate-limit';
import { FieldValue } from 'firebase-admin/firestore';
import { processWithGemini } from '../lib/gemini.js';
import { log } from '../lib/logger.js';
import { detectAndTranslate } from '../lib/translate.js';

export function processRouter(db) {
  const router = Router();

  // Firestore collection for audit logging of all processed requests
  const requests = db.collection('requests');

  /**
   * Rate limiter: 20 requests per minute per IP.
   * Prevents API abuse and controls Gemini API costs.
   * Uses standard RateLimit headers (RFC 6585) so clients can self-throttle.
   */
  const limiter = rateLimit({
    windowMs: 60 * 1000,
    max: 20,
    standardHeaders: true,
    legacyHeaders: false,
    message: { error: 'Too many requests. Please wait a moment and try again.' },
  });

  router.post('/', limiter, async (req, res) => {
    // Random request ID for correlating logs across the request lifecycle
    const requestId = Math.random().toString(36).substring(2, 15);

    log('info', 'Processing request', { requestId, type: req.body.type });

    try {
      const { type, imageData, mimeType } = req.body;
      let { content } = req.body;

      // Require at least one input modality
      if (!content && !imageData) {
        log('warn', 'Missing content or imageData', { requestId });
        return res.status(400).json({ error: 'content or imageData is required' });
      }

      // Google Cloud Translation: auto-detect and translate non-English input
      // so Gemini can process inputs from any language, broadening global reach
      let detectedLanguage = null;
      if (content) {
        const translated = await detectAndTranslate(content);
        content = translated.text;
        detectedLanguage = translated.detectedLanguage;
        if (detectedLanguage) {
          log('info', 'Translated input', { requestId, detectedLanguage });
        }
      }

      log('debug', 'Calling Gemini API', {
        requestId,
        type,
        contentLength: content?.length || 0,
        hasImage: !!imageData,
      });

      // Call Gemini via the backend proxy — API key never leaves the server
      const parsed = await processWithGemini({ type, content, imageData, mimeType });

      log('info', 'Request successful', {
        requestId,
        actionCount: parsed.actions.length,
        urgency: parsed.actions[0]?.urgency || 'info',
      });

      /**
       * Async Firestore write — intentionally fire-and-forget.
       * The response is sent immediately; a logging failure should never
       * degrade the user experience. Input is truncated to 500 chars to
       * keep storage costs and PII exposure minimal.
       */
      requests.add({
        type: type || 'text',
        input: content ? content.slice(0, 500) : '[image]',
        summary: parsed.summary,
        actionCount: parsed.actions.length,
        urgency: parsed.actions[0]?.urgency || 'info',
        detectedLanguage,
        timestamp: FieldValue.serverTimestamp(),
      }).catch(err => log('warn', 'Firestore write failed (non-fatal)', { requestId, error: err.message }));

      return res.json({ ...parsed, detectedLanguage });

    } catch (error) {
      log('error', 'Error processing request', {
        requestId,
        error: error.message,
        stack: error.stack,
      });

      const message = error instanceof Error ? error.message : 'Internal server error';
      return res.status(500).json({ error: message });
    }
  });

  return router;
}
